# Generated by Django 5.0 on 2024-01-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccountCashBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_balance_in_account",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Saldo em conta total (US$)",
                    ),
                ),
                (
                    "balance_in_national_currency",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Saldo moeda nacional (US$)",
                    ),
                ),
                (
                    "balance_in_foreign_currency",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Saldo moeda estrangeira (US$)",
                    ),
                ),
                (
                    "percent_balance_in_foreign_currency",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="% Saldo em conta moeda estrangeira",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "symbol",
                    models.CharField(max_length=255, verbose_name="Ativo"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=10,
                        max_digits=20,
                        verbose_name="Quantidade",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=10,
                        max_digits=20,
                        verbose_name="Valor (US$)",
                    ),
                ),
                (
                    "fees",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Custos (US$)",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Positions",
            fields=[
                (
                    "symbol",
                    models.CharField(
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "total_quantity",
                    models.DecimalField(
                        decimal_places=10,
                        max_digits=20,
                        verbose_name="Quantidade",
                    ),
                ),
                (
                    "average_value",
                    models.DecimalField(
                        decimal_places=10,
                        max_digits=20,
                        verbose_name="Valor médio (US$)",
                    ),
                ),
            ],
        ),
    ]
