# Generated by Django 5.0.1 on 2024-01-14 15:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("positions", "0002_auto_20240111_1936"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="fees",
        ),
    ]
