# Generated by Django 4.2.8 on 2023-12-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entry_type", models.CharField(max_length=255)),
                ("national_balance_value_before", models.FloatField()),
                ("national_balance_value_after", models.FloatField()),
                ("foreign_balance_value_before", models.FloatField()),
                ("foreign_balance_value_after", models.FloatField()),
                ("total_balance_value_before", models.FloatField()),
                ("total_balance_value_after", models.FloatField()),
                ("date", models.DateField()),
                ("time", models.TimeField()),
            ],
        ),
    ]
