# Generated by Django 5.0.1 on 2024-01-14 15:20

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("home", "0006_alter_brokerageasset_operation"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrokerageHistory",
            fields=[
                (
                    "brokerageasset_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="home.brokerageasset",
                    ),
                ),
                (
                    "total_balance_in_account",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Saldo em conta total (US$)",
                    ),
                ),
                (
                    "balance_in_national_currency",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Saldo moeda nacional (US$)",
                    ),
                ),
                (
                    "balance_in_foreign_currency",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Saldo moeda estrangeira (US$)",
                    ),
                ),
                (
                    "percent_balance_in_foreign_currency",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="% Saldo em conta moeda estrangeira",
                    ),
                ),
            ],
            bases=("home.brokerageasset",),
        ),
    ]
