# Generated by Django 4.1.3 on 2022-12-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(max_length=255)),
                ('national_wallet_value_before', models.FloatField()),
                ('national_wallet_value_after', models.FloatField()),
                ('foreign_wallet_value_before', models.FloatField()),
                ('foreign_wallet_value_after', models.FloatField()),
                ('total_wallet_value_before', models.FloatField()),
                ('total_wallet_value_after', models.FloatField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
