# Generated by Django 4.2.8 on 2023-12-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BrokerageAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("Deposit", "Deposit"),
                            ("Buy", "Buy"),
                            ("Sell", "Sell"),
                            ("Dividend", "Dividend"),
                            ("Tax Paid", "Tax Paid"),
                            ("Interest", "Interest"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("asset", models.CharField(max_length=255)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=10, max_digits=20),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "costs",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "total_in_usd",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "origin_in_national_currency",
                    models.CharField(max_length=255),
                ),
                (
                    "origin_in_foreign_currency",
                    models.CharField(max_length=255),
                ),
                (
                    "for_purchase_exchange_sell",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "for_sale_exchange_purchase",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "profit_in_r",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "balance_in_national_currency",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "balance_in_foreign_currency",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "total_balance_in_account",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "percent_balance_in_foreign_currency",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
            ],
        ),
    ]
