# Generated by Django 5.0 on 2023-12-27 00:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brokerageasset",
            name="costs",
        ),
        migrations.RemoveField(
            model_name="brokerageasset",
            name="profit_in_r",
        ),
        migrations.RemoveField(
            model_name="brokerageasset",
            name="total_in_usd",
        ),
        migrations.AddField(
            model_name="brokerageasset",
            name="fees",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Custos (R$)",
            ),
        ),
        migrations.AddField(
            model_name="brokerageasset",
            name="profit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Lucro (R$)",
            ),
        ),
        migrations.AddField(
            model_name="brokerageasset",
            name="purchase_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Valor da compra (R$)",
            ),
        ),
        migrations.AddField(
            model_name="brokerageasset",
            name="sell_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Valor da venda (R$)",
            ),
        ),
        migrations.AddField(
            model_name="brokerageasset",
            name="total",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Total (US$)",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="brokerageasset",
            name="asset",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Ativo"
            ),
        ),
        migrations.AlterField(
            model_name="brokerageasset",
            name="balance_in_foreign_currency",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                verbose_name="Saldo moeda estrangeira (US$)",
            ),
        ),
        migrations.AlterField(
            model_name="brokerageasset",
            name="balance_in_national_currency",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                verbose_name="Saldo moeda nacional (US$)",
            ),
        ),
        migrations.AlterField(
            model_name="brokerageasset",
            name="date",
            field=models.DateField(auto_created=True, verbose_name="Data"),
        ),
        migrations.AlterField(
            model_name="brokerageasset",
            name="for_purchase_exchange_sell",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=10,
                null=True,
                verbose_name="Para compra, câmbio de venda (R$)",
            ),
        ),
        migrations.AlterField(
            model_name="brokerageasset",
            name="for_sale_exchange_purchase",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=10,
                null=True,
                verbose_name="Para venda, câmbio de compra (R$)",
            ),
        ),
        migrations.AlterField(
            model_name="brokerageasset",
            name="operation",
            field=models.CharField(
                choices=[
                    ("Deposit", "Deposit"),
                    ("Buy", "Buy"),
                    ("Sell", "Sell"),
                    ("Dividend", "Dividend"),
                    ("Tax Paid", "Tax Paid"),
                    ("Interest", "Interest"),
                    ("Other", "Other"),
                ],
                max_length=20,
                verbose_name="Operação",
            ),
        ),
        migrations.AlterField(
            model_name="brokerageasset",
            name="origin_in_foreign_currency",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Origem moeda estrangeira (US$)",
            ),
        ),
        migrations.AlterField(
            model_name="brokerageasset",
            name="origin_in_national_currency",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Origem moeda nacional (US$)",
            ),
        ),
        migrations.AlterField(
            model_name="brokerageasset",
            name="percent_balance_in_foreign_currency",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                verbose_name="% Saldo em conta moeda estrangeira",
            ),
        ),
        migrations.AlterField(
            model_name="brokerageasset",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Preço (US$)",
            ),
        ),
        migrations.AlterField(
            model_name="brokerageasset",
            name="quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                max_digits=20,
                null=True,
                verbose_name="Quantidade",
            ),
        ),
        migrations.AlterField(
            model_name="brokerageasset",
            name="total_balance_in_account",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                verbose_name="Saldo em conta total (US$)",
            ),
        ),
    ]
