# Generated by Django 5.0 on 2023-12-27 01:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_remove_brokerageasset_costs_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brokerageasset",
            name="date",
            field=models.DateField(verbose_name="Data"),
        ),
    ]
