# Generated by Django 4.1.3 on 2022-12-17 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_value', models.FloatField()),
                ('foreign_value', models.FloatField()),
                ('last_addition', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WalletIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('national_fee', models.FloatField()),
                ('exchange_value', models.FloatField()),
                ('foreign_fee', models.FloatField()),
                ('is_dividend', models.BooleanField()),
                ('is_foreign', models.BooleanField()),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='history.history')),
            ],
        ),
    ]
