# Generated by Django 4.1.3 on 2022-12-17 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IRBaseSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.FloatField()),
                ('is_percentage', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='IRDividendSettings',
            fields=[
                ('irbasesettings_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gov.irbasesettings')),
                ('fee_type', models.CharField(default='Provento', max_length=255)),
            ],
            bases=('gov.irbasesettings',),
        ),
        migrations.CreateModel(
            name='IR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('paid', models.BooleanField()),
                ('due_date', models.DateField()),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='history.history')),
            ],
        ),
    ]
